
#define IDD_PROPERTY_SHEET          100

#define IDDI_PROPERTY_SHEET_TREEVIEW   121
#define IDDI_PROPERTY_SHEET_OK         122
#define IDDI_PROPERTY_SHEET_CANCEL     123

#define TREEVIEW_WIDTH (128 + 64)
